<a href="https://colab.research.google.com/github/AhnJG/AI-Project/blob/master/Colab/Calc_of_loss_and_error.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
# sparse_categorical_crossentropy
y_true = [1, 2]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
print(loss)

tf.Tensor([0.05129344 2.3025851 ], shape=(2,), dtype=float32)


In [6]:
# categorical_crossentropy
y_true = [[0, 1, 0], [0, 0, 1]]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
loss = tf.keras.losses.categorical_crossentropy(y_true, y_pred)
print(loss)

tf.Tensor([0.05129331 2.3025851 ], shape=(2,), dtype=float32)


In [11]:
y_true = [[0, 1, 0], [0, 0.5, 0.5]]
y_pred = [[0.05, 0.95, 0], [0.02, 0.49, 0.49]]
loss = tf.keras.losses.categorical_crossentropy(y_true, y_pred)
print(loss)

tf.Tensor([0.05129331 0.7133499 ], shape=(2,), dtype=float32)


In [16]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_squared_log_error

y_true = [60, 80, 90]
y_pred = [67, 78, 91]
RMSE = np.sqrt(mean_squared_error(y_true, y_pred))
print("RMSE :", RMSE)

RMSLE = np.sqrt(mean_squared_log_error(y_true, y_pred))
print("RMSLE :", RMSLE)

RMSE : 4.242640687119285
RMSLE : 0.0646679237996832


In [19]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_squared_log_error

y_true = [60, 80, 90, 750]
y_pred = [67, 78, 91, 102]
RMSE = np.sqrt(mean_squared_error(y_true, y_pred))
print("RMSE :", RMSE)

RMSLE = np.sqrt(mean_squared_log_error(y_true, y_pred))
print("RMSLE :", RMSLE)

RMSE : 324.02083266358045
RMSLE : 0.9949158238939428


In [20]:
y_true = [90]
y_pred = [100]
RMSE = np.sqrt(mean_squared_error(y_true, y_pred))
print("RMSE :", RMSE)

RMSLE = np.sqrt(mean_squared_log_error(y_true, y_pred))
print("RMSLE :", RMSLE)

RMSE : 10.0
RMSLE : 0.10426101032440993


In [21]:
y_true = [9000]
y_pred = [10000]
RMSE = np.sqrt(mean_squared_error(y_true, y_pred))
print("RMSE :", RMSE)

RMSLE = np.sqrt(mean_squared_log_error(y_true, y_pred))
print("RMSLE :", RMSLE)

RMSE : 1000.0
RMSLE : 0.10534940571943174


In [22]:
y_true = [1000]
y_pred = [600]
RMSE = np.sqrt(mean_squared_error(y_true, y_pred))
print("RMSE :", RMSE)

RMSLE = np.sqrt(mean_squared_log_error(y_true, y_pred))
print("RMSLE :", RMSLE)

RMSE : 400.0
RMSLE : 0.5101598447800129


In [23]:
y_true = [1000]
y_pred = [1400]
RMSE = np.sqrt(mean_squared_error(y_true, y_pred))
print("RMSE :", RMSE)

RMSLE = np.sqrt(mean_squared_log_error(y_true, y_pred))
print("RMSLE :", RMSLE)

RMSE : 400.0
RMSLE : 0.3361867670217862


In [26]:
y_true = [10000000000]
y_pred = [100000000]

RMSLE = np.sqrt(mean_squared_log_error(y_true, y_pred))
print("RMSLE :", RMSLE)

RMSLE : 4.605170176088091
